app/bot/views.py
import logging
import json
from flask import Blueprint, current_app, request
import requests
from twilio.twiml.messaging_response import MessagingResponse
from .util import detect_intent_texts, detect_intent_knowledge
from app.extensions import csrf_protect

blueprint = Blueprint('bot', __name__, url_prefix='/bot')


# logging.getLogger('flask_assistant').setLevel(logging.DEBUG)


@blueprint.route('/twilio', methods=['POST'])
@csrf_protect.exempt
def twilio():
    incoming_msg = request.values.get('Body', '').lower()
    resp = MessagingResponse()
    msg = resp.message()
    responded = False
    intent = detect_intent_knowledge(project_id="astrix",
                                 session_id="123",
                                 texts=[incoming_msg],
                                 language_code="en-US")
    msg.body(intent.query_result.fulfillment_text)
    responded = True
    return str(resp)

@blueprint.route('/web', methods=['POST'])
@csrf_protect.exempt
def web():
    incoming_msg = request.values.get('msg')
    print(incoming_msg)
    intent = detect_intent_texts(project_id="astrix",
                                 session_id="123",
                                 texts=[incoming_msg],
                                 language_code="en-US")
    return intent.query_result.fulfillment_text

@blueprint.route('/twilio_old', methods=['POST'])
@csrf_protect.exempt
def twilio_old():
    incoming_msg = request.values.get('Body', '').lower()
    resp = MessagingResponse()
    msg = resp.message()
    responded = False
    if 'quote' in incoming_msg:
        # return a quote
        r = requests.get('https://api.quotable.io/random')
        if r.status_code == 200:
            data = r.json()
            quote = f'{data["content"]} ({data["author"]})'
        else:
            quote = 'I could not retrieve a quote at this time, sorry.'
        msg.body(quote)
        responded = True
    if 'cat' in incoming_msg:
        # return a cat pic
        msg.media('https://cataas.com/cat')
        responded = True
    if not responded:
        msg.body('I only know about famous quotes and cats, sorry!')
    return str(resp)

@blueprint.route('/new_lead', methods=['POST'])
@csrf_protect.exempt
def new_lead():
    incoming_msg = request.values.get('Body', '').lower()
    print(request)
    return

app/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

app/templates/footer.html
<!-- ========== FOOTER ========== -->
<footer class="bg-navy">
  <div class="container space-2">
    <div class="row justify-content-center mb-2">
      <div class="col-lg-3 mb-5 mb-lg-0">
        <!-- Logo -->
        <a href="#" aria-label="Astrix">
          <img class="brand" src="{{ url_for('static', filename='svg/logos/Transparent_Logo-03.png') }}" alt="Astrix">
        </a>
        <!-- End Logo -->
      </div>

      {#<div class="col-6 col-md-3 col-lg-2 mb-5 mb-lg-0">
        <h5 class="text-white font-weight-bold">Help and advice</h5>
        <!-- Nav Links -->
        <ul class="nav nav-sm nav-x-0 nav-white flex-column">
          <li class="nav-item"><a class="nav-link" href="{{ url_for('public.contact') }}">Contact us</a></li>
          <li class="nav-item"><a class="nav-link" href="#">FAQ</a></li>
          <li class="nav-item"><a class="nav-link" href="#">Legal & Privacy</a></li>
        </ul>
        <!-- End Nav Links -->
      </div>

      <div class="col-6 col-md-3 col-lg-2 mb-5 mb-lg-0">
        <h5 class="text-white font-weight-bold">About us</h5>
        <!-- Nav Links -->
        <ul class="nav nav-sm nav-x-0 nav-white flex-column">
          <li class="nav-item"><a class="nav-link" href="#">About Spec</a></li>
          <li class="nav-item"><a class="nav-link" href="#">Careers</a></li>
        </ul>
        <!-- End Nav Links -->
      </div>

      <div class="col-md-6 col-lg-5">
        <!-- Form -->
        <form class="js-validate mb-2">
          <h5 class="text-white font-weight-bold mb-3">Stay up to date</h5>
          <div class="form-row">
            <div class="col">
              <div class="js-form-message">
                <label class="sr-only" for="subscribeSrEmail">Email address</label>
                <div class="input-group">
                  <input type="email" class="form-control" name="email" id="subscribeSrEmail" placeholder="Email address" aria-label="Email address" required
                         data-msg="Please enter a valid email address.">
                </div>
              </div>
            </div>

            <div class="col-auto">
              <button type="submit" class="btn btn-primary">
                <i class="fas fa-arrow-right"></i>
              </button>
            </div>
          </div>
        </form>
        <!-- End Form -->

        <p class="text-white-70 small mb-0">Marketing tips &amp; tricks. Never spam.</p>
      </div>#}
    </div>

    <!-- Copyright -->
    <div class="row justify-content-center">
      {#<div class="col-md-6 mb-4 mb-md-0">#}
        <p class="small text-white-70 mb-0">© Astrix 2020. All rights reserved.</p>
      {#</div>#}

      {#<div class="col-md-6 text-md-right">
        <!-- Social Networks -->
        <!--<ul class="list-inline mb-0">
          <li class="list-inline-item mb-2 mb-sm-0">
            <a class="btn btn-xs btn-icon btn-ghost-light" href="#">
              <i class="fab fa-facebook-f"></i>
            </a>
          </li>
          <li class="list-inline-item mb-2 mb-sm-0">
            <a class="btn btn-xs btn-icon btn-ghost-light" href="#">
              <i class="fab fa-google"></i>
            </a>
          </li>
          <li class="list-inline-item mb-2 mb-sm-0">
            <a class="btn btn-xs btn-icon btn-ghost-light" href="#">
              <i class="fab fa-twitter"></i>
            </a>
          </li>
          <li class="list-inline-item mb-2 mb-sm-0">
            <a class="btn btn-xs btn-icon btn-ghost-light" href="#">
              <i class="fab fa-github"></i>
            </a>
          </li>
          <li class="list-inline-item mb-2 mb-sm-0">
            <a class="btn btn-xs btn-icon btn-ghost-light" href="#">
              <i class="fab fa-linkedin"></i>
            </a>
          </li>
        </ul>-->
        <!-- End Social Networks -->
      </div>#}
    </div>
    <!-- End Copyright -->
  </div>
</footer>
<!-- ========== END FOOTER ========== -->

app/templates/layout.html
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en">
  <!--<![endif]-->
  <head>
    <meta charset="utf-8" />
    <title>
      {% block page_title %}
      Astrix
       {% endblock %}
    </title>
    <meta
      name="description"
      content="{% block meta_description %}{% endblock %}"
    />
    <meta name="author" content="{% block meta_author %}{% endblock %}" />

    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="width=device-width" />

    <!-- Favicon -->
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">

    <!-- Font -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600&display=swap" rel="stylesheet">

    <!-- CSS Implementing Plugins -->
    <link rel="stylesheet" href="{{ url_for('static', filename='vendor/font-awesome/css/all.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='vendor/hs-mega-menu/dist/hs-mega-menu.min.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='vendor/aos/dist/aos.css') }}">

    <!-- CSS Chat Template -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/chat.css') }}">

    <!-- CSS Astrix Template -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/theme.css') }}">

    {% block css %}{% endblock %}
  </head>
  <body class="{% block body_class %}{% endblock %}">
    {% block body %} {% with form=form %} {% include "nav.html" %} {% endwith %}

    <header>{% block header %}{% endblock %}</header>

    <main role="main">
      {% block content %}{% endblock %}
      {% include 'public/widgets/chat.html' %}
    </main>

    {% include "footer.html" %}

    <!-- JS Global Compulsory -->
    <script src="{{ url_for('static', filename='vendor/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/jquery-migrate/dist/jquery-migrate.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>

    <!-- JS Implementing Plugins -->
    <script src="{{ url_for('static', filename='vendor/hs-header/dist/hs-header.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/hs-go-to/dist/hs-go-to.min.js') }}"></script>
    <!--<script src="../assets/vendor/hs-mega-menu/dist/hs-mega-menu.min.js"></script>-->
    <script src="{{ url_for('static', filename='vendor/jquery-validation/dist/jquery.validate.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/aos/dist/aos.js') }}"></script>

    <!-- JS Astrix -->
    <script src="{{ url_for('static', filename='js/hs.core.js') }}"></script>
    <script src="{{ url_for('static', filename='js/hs.validation.js') }}"></script>

    <!-- JS Plugins Init. -->
    <script>
      $(document).on('ready', function () {
        // initialization of header
        //var header = new HSHeader($('#header')).init();

        // initialization of mega menu
        //var megaMenu = new HSMegaMenu($('.js-mega-menu'), {
        //  desktop: {
        //    position: 'left'
        //  }
        //}).init();

        // initialization of form validation
        $('.js-validate').each(function() {
          $.HSCore.components.HSValidation.init($(this));
        });

        // initialization of aos
        AOS.init({
          duration: 650,
          once: true
        });

        // initialization of go to
        $('.js-go-to').each(function () {
          var goTo = new HSGoTo($(this)).init();
        });
      });
    </script>

    <script>
      $(function() {
        var INDEX = 0;
        $("#chat-submit").click(function(e) {
          e.preventDefault();
          var msg = $("#chat-input").val();
          if(msg.trim() == ''){
            return false;
          }
          generate_message(msg, 'self');
          send_message(msg);
        })

        function generate_message(msg, type) {
          INDEX++;
          var str="";
          str += "<div id='cm-msg-"+INDEX+"' class=\"chat-msg "+type+"\">";
          str += "          <div class=\"cm-msg-text\">";
          str += msg;
          str += "          <\/div>";
          str += "        <\/div>";
          $(".chat-logs").append(str);
          $("#cm-msg-"+INDEX).hide().fadeIn(100);
          if(type == 'self'){
           $("#chat-input").val('');
          }
          $(".chat-logs").stop().animate({ scrollTop: $(".chat-logs")[0].scrollHeight}, 1000);
        }

        function generate_button_message(msg, buttons){
          /* Buttons should be object array
            [
              {
                name: 'Existing User',
                value: 'existing'
              },
              {
                name: 'New User',
                value: 'new'
              }
            ]
          */
          INDEX++;
          var btn_obj = buttons.map(function(button) {
             return  "              <li class=\"button\"><a href=\"javascript:;\" class=\"btn btn-primary chat-btn\" chat-value=\""+button.value+"\">"+button.name+"<\/a><\/li>";
          }).join('');
          var str="";
          str += "<div id='cm-msg-"+INDEX+"' class=\"chat-msg user\">";
          str += "          <span class=\"msg-avatar\">";
          str += "            <img src=\"https:\/\/image.crisp.im\/avatar\/operator\/196af8cc-f6ad-4ef7-afd1-c45d5231387c\/240\/?1483361727745\">";
          str += "          <\/span>";
          str += "          <div class=\"cm-msg-text\">";
          str += msg;
          str += "          <\/div>";
          str += "          <div class=\"cm-msg-button\">";
          str += "            <ul>";
          str += btn_obj;
          str += "            <\/ul>";
          str += "          <\/div>";
          str += "        <\/div>";
          $(".chat-logs").append(str);
          $("#cm-msg-"+INDEX).hide().fadeIn(300);
          $(".chat-logs").stop().animate({ scrollTop: $(".chat-logs")[0].scrollHeight}, 1000);
          $("#chat-input").attr("disabled", true);
        }

        function send_message(msg) {
          $.ajax({
            type: "POST",
            url: "{{ url_for('bot.web') }}",
            data: { msg: msg}
          }).done(function( data ) {
            generate_message(data, 'user');
          });
        }

        function getJSessionId(){
          var jsId = document.cookie.match(/JSESSIONID=[^;]+/);
          if(jsId != null) {
              if (jsId instanceof Array)
                  jsId = jsId[0].substring(11);
              else
                  jsId = jsId.substring(11);
          }
          return jsId;
      }

        $(document).delegate(".chat-btn", "click", function() {
          var value = $(this).attr("chat-value");
          var name = $(this).html();
          $("#chat-input").attr("disabled", false);
          generate_message(name, 'self');
        })

        $("#chat-circle").click(function() {
          $("#chat-circle").toggle('scale');
          $(".chat-box").toggle('scale');
        })

        $(".chat-box-toggle").click(function() {
          $("#chat-circle").toggle('scale');
          $(".chat-box").toggle('scale');
        })

      });
    </script>

    <!-- JS Global Compulsory -->
    <script src="{{ url_for('static', filename='vendor/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/jquery-migrate/dist/jquery-migrate.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/bootstrap/dist/js/bootstrap.bundle.min.js') }}"></script>

    <!-- JS Implementing Plugins -->
    <script src="{{ url_for('static', filename='vendor/hs-header/dist/hs-header.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/hs-go-to/dist/hs-go-to.min.js') }}"></script>
    <!--<script src="../assets/vendor/hs-mega-menu/dist/hs-mega-menu.min.js"></script>-->
    <script src="{{ url_for('static', filename='vendor/jquery-validation/dist/jquery.validate.min.js') }}"></script>
    <script src="{{ url_for('static', filename='vendor/aos/dist/aos.js') }}"></script>

    <!-- JS Astrix -->
    <script src="{{ url_for('static', filename='js/hs.core.js') }}"></script>
    <script src="{{ url_for('static', filename='js/hs.validation.js') }}"></script>
    {% block js %}{% endblock %}
    <!-- end scripts -->
    {% endblock %}
  </body>
</html>

app/templates/nav.html
<!-- ========== HEADER ========== -->
<header id="header" class="header header-box-shadow-on-scroll header-abs-top-lg header-show-hide-lg"
        data-hs-header-options='{
          "fixMoment": 1000,
          "fixEffect": "slide"
        }'>
  <div class="header-section">
    <div id="logoAndNav" class="container">
      <!-- Nav -->
      <nav class="js-mega-menu navbar navbar-expand-lg">
        <!-- Logo -->
        <a class="navbar-brand" href="{{ url_for('public.home') }}" aria-label="Astrix">
          <img src="{{ url_for('static', filename='svg/logos/Transparent_Logo-03.png') }}" alt="Logo">
        </a>
        <!-- End Logo -->

        <!-- Responsive Toggle Button -->
        <button type="button" class="navbar-toggler btn btn-icon btn-sm rounded-circle"
                aria-label="Toggle navigation"
                aria-expanded="false"
                aria-controls="navBar"
                data-toggle="collapse"
                data-target="#navBar">
          <span class="navbar-toggler-default">
            <svg width="14" height="14" viewBox="0 0 18 18" xmlns="http://www.w3.org/2000/svg">
              <path fill="currentColor" d="M17.4,6.2H0.6C0.3,6.2,0,5.9,0,5.5V4.1c0-0.4,0.3-0.7,0.6-0.7h16.9c0.3,0,0.6,0.3,0.6,0.7v1.4C18,5.9,17.7,6.2,17.4,6.2z M17.4,14.1H0.6c-0.3,0-0.6-0.3-0.6-0.7V12c0-0.4,0.3-0.7,0.6-0.7h16.9c0.3,0,0.6,0.3,0.6,0.7v1.4C18,13.7,17.7,14.1,17.4,14.1z"/>
            </svg>
          </span>
          <span class="navbar-toggler-toggled">
            <svg width="14" height="14" viewBox="0 0 18 18" xmlns="http://www.w3.org/2000/svg">
              <path fill="currentColor" d="M11.5,9.5l5-5c0.2-0.2,0.2-0.6-0.1-0.9l-1-1c-0.3-0.3-0.7-0.3-0.9-0.1l-5,5l-5-5C4.3,2.3,3.9,2.4,3.6,2.6l-1,1 C2.4,3.9,2.3,4.3,2.5,4.5l5,5l-5,5c-0.2,0.2-0.2,0.6,0.1,0.9l1,1c0.3,0.3,0.7,0.3,0.9,0.1l5-5l5,5c0.2,0.2,0.6,0.2,0.9-0.1l1-1 c0.3-0.3,0.3-0.7,0.1-0.9L11.5,9.5z"/>
            </svg>
          </span>
        </button>
        <!-- End Responsive Toggle Button -->

        <!-- Navigation -->
        <div id="navBar" class="collapse navbar-collapse">
          <div class="navbar-body header-abs-top-inner">
            <ul class="navbar-nav">
              <!-- Home -->
              <li class="navbar-nav-item">
                <a id="home" class="nav-link" href="{{ url_for('public.home') }}" aria-expanded="false">Home</a>
              </li>
              <!-- End Home -->
              {#<!-- Features -->
              <li class="navbar-nav-item">
                <a id="home" class="nav-link" href="features.html" aria-expanded="false">Features</a>
              </li>
              <!-- End Features -->#}
              <!-- Contact -->
              <li class="navbar-nav-item">
                <a id="home" class="nav-link" href="{{ url_for('public.contact') }}" aria-expanded="false">Contact</a>
              </li>
              <!-- End Contact -->

              <!-- Button -->
              <li class="navbar-nav-last-item">
                {% with class="btn btn-sm btn-primary transition-3d-hover" %}
                {% include 'public/widgets/calendly.html' %}
                {% endwith %}
              </li>
              <!-- End Button -->
            </ul>
          </div>
        </div>
        <!-- End Navigation -->
      </nav>
      <!-- End Nav -->
    </div>
  </div>
</header>
<!-- ========== END HEADER ========== -->